In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("ArtificialPatientTreatment.csv")

In [6]:
df

        patient           action  org:resource              DateTime
0     patient 0    First consult      Dr. Anna   2017-01-02 11:40:11
1     patient 0       Blood test           Lab   2017-01-02 12:47:33
2     patient 0    Physical test   Nurse Jesse   2017-01-02 12:53:50
3     patient 0   Second consult      Dr. Anna   2017-01-02 16:21:06
4     patient 0          Surgery   Dr. Charlie   2017-01-05 13:23:09
..          ...              ...           ...                   ...
685  patient 99       X-ray scan        Team 2   2017-05-25 11:03:27
686  patient 99    Physical test   Nurse Corey   2017-05-25 11:55:24
687  patient 99   Second consult      Dr. Anna   2017-05-29 15:12:39
688  patient 99         Medicine      Pharmacy   2017-05-29 16:17:13
689  patient 99    Final consult      Dr. Anna   2017-05-31 12:46:43

[690 rows x 4 columns]

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.shape

(690, 4)

In [14]:
df.describe()

          patient          action  org:resource              DateTime
count         690             690           690                   690
unique        100               8            13                   690
top     patient 1   First consult      Dr. Anna   2017-01-02 11:40:11
freq            7             100           158                     1